"""rename librarian password field to hashed_password

Revision ID: 2f0be826a996
Revises: 1f279d6c786e
Create Date: 2025-06-14 06:34:37.895497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0be826a996'
down_revision: Union[str, None] = '1f279d6c786e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('librarians', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('librarians', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('librarians', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('librarians', 'hashed_password')
    # ### end Alembic commands ###
